Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,10 +22,6 @@ jobs:
 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
-      # Checkout the source code
-      - name: 'Checkout source code'
-        uses: actions/checkout@v2
-      
       # Install Salesforce CLI
       - name: Install Salesforce CLI
         run: |
@@ -34,6 +30,21 @@ jobs:
             tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
             ./sfdx-cli/install
 
+      # Checkout the source code
+      - name: 'Checkout source code'
+        uses: actions/checkout@v2
+
+      # Store secret for dev hub
+      - name: 'Populate auth file with DEVHUB_SFDX_URL secret'
+        shell: bash
+        run: |
+            echo ${{ secrets.SFDX_AUTH_URL }} > ./SFDX_AUTH_URL.txt
+            secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
+            if [ $secretFileSize == 1 ]; then
+                echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
+                exit 1;
+            fi
+
       # Runs a set of commands using the runners shell
       - name: Authorize org
-        run: sfdx force:auth:sfdxurl:store -f ${{ secrets.SFDX_AUTH_URL }} -s -a github_actions_org
+        run: sfdx force:auth:sfdxurl:store -f ./SFDX_AUTH_URL.txt -s -a github_actions_org
